repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: format
        name: Format
        entry: npm run format
        language: system
        pass_filenames: false
      - id: lint
        name: Lint
        entry: npm run lint
        types: [ts, python]
        language: system
        pass_filenames: false
      - id: typecheck
        name: Typecheck
        entry: npm run typecheck
        types: [ts, python]
        language: system
        pass_filenames: false
